package Solution;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import javax.swing.WindowConstants;
import java.awt.Dimension;

public class OnlyARoom extends JFrame {

  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      {
        int newx = 0;
        int newy = 0;
        int oldx = 250;
        int oldy = 250;
        int dir = 1;
        graphics.drawOval(oldx, oldy, 10, 10);

        newy = moveForwardY(oldy, dir, 10);
        newx = moveForwardX(oldx, dir, 10);
        graphics.drawLine(oldx, oldy, newx, newy);
        oldx = newx;
        oldy = newy;
        graphics.drawOval(oldx, oldy, 10, 10);
      }
    }


  };

  private void initialize() {
    this.setTitle("OnlyARoom");
    this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public int moveForwardX(int x, int dir, int dist) {
    switch (dir) {
      case 1:
        return x - dist;
      case 3:
        return x + dist;
      default:
        return x;
    }
  }
  public int moveForwardY(int x, int dir, int dist) {
    switch (dir) {
      case 0:
        return x - dist;
      case 2:
        return x + dist;
      default:
        return x;
    }
  }


  public static void main(String[] args) {
    OnlyARoom room = new OnlyARoom();
    room.initialize();
  }


}
