package Solution;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import java.awt.Dimension;

public class OnlyARoom extends JFrame {

  private JPanel panel = new JPanel() {};

  private void initialize() {
    this.setTitle("OnlyARoom");
    this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    OnlyARoom room = new OnlyARoom();
    room.initialize();
  }

}
