package Solution;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import javax.swing.WindowConstants;
import java.awt.Dimension;

public class OnlyARoom extends JFrame {

  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
    }


  };

  private int width;
  private int height;
  private void initialize() {
    this.setTitle("OnlyARoom");
    this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    this.add(panel);
    width = 500;
    height = 500;
    panel.setPreferredSize(new Dimension(width, height));
    this.pack();
    this.setVisible(true);
  }

  public int moveForwardX(int x, int dir, int dist) {
    int r = x;
    System.out.println("moveX");
    System.out.println(dir);

    switch (dir) {
      case 3:
        System.out.println("case 3");
        r = x - dist;
        break;
      case 1:
        System.out.println("case 1");

        r = x + dist;
        break;
      default:
        System.out.println("case 0 or 2");

    }
    if (r > width) {
      r = width - 5;
    }
    if (r <= 0) {
      r = 5;
    }

    return r;
  }
  public int moveForwardY(int y, int dir, int dist) {
    int r = y;
    System.out.println("moveY");
    System.out.println(dir);

    switch (dir) {
      case 0:
        System.out.println("case 0");

        r = y - dist;
        break;
      case 2:
        System.out.println("case 2");

        r = y + dist;
        break;
      default:
        System.out.println("case 1 or 3");

    }
    if (r > height) {
      r = height - 5;
    }
    if (r <= 0) {
      r = 5;
    }
    return r;
  }


  public static void main(String[] args) {
    OnlyARoom room = new OnlyARoom();
    room.initialize();
  }


}
