package RobotLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Action = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Jump = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Look = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Move = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Robot = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Room = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Turn = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Action;
      case 1:
        return props_Jump;
      case 2:
        return props_Look;
      case 3:
        return props_Move;
      case 4:
        return props_Robot;
      case 5:
        return props_Room;
      case 6:
        return props_Turn;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
